"""
One-click launcher for the backtest UI.

Starts the FastAPI server (which serves both the API and the prebuilt UI from
``ui/build/``) and opens a browser tab. Requires only Python — no Node.js at
runtime, provided ``ui/build/`` has already been generated by ``npm run build``.

Usage:
    python run_backtest_ui.py
    API_PORT=9000 python run_backtest_ui.py   # override port
"""

from __future__ import annotations

import os
import sys
import threading
import time
import webbrowser
from pathlib import Path

import uvicorn

ROOT = Path(__file__).resolve().parent
UI_BUILD = ROOT / "ui" / "build"


def _open_browser(url: str) -> None:
    time.sleep(1.5)
    webbrowser.open(url)


def main() -> None:
    if not UI_BUILD.is_dir():
        print(
            f"ERROR: UI bundle not found at {UI_BUILD}\n\n"
            "Build it once on a machine with Node.js:\n"
            "    cd ui && npm ci && npm run build\n\n"
            "Then re-run this launcher. Node is not needed at runtime.",
            file=sys.stderr,
        )
        sys.exit(1)

    port = int(os.getenv("API_PORT", "8100"))
    host = os.getenv("API_HOST", "127.0.0.1")
    url = f"http://localhost:{port}"

    print(f"Starting backtest UI on {url} ...")
    threading.Thread(target=_open_browser, args=(url,), daemon=True).start()

    uvicorn.run(
        "app.api.main:app",
        host=host,
        port=port,
        reload=False,
        log_level="info",
    )


if __name__ == "__main__":
    main()
