"""
Auto-generate docs/database.md from ORM models.

Usage:
    python scripts/gen_db_docs.py

Design rationale lives as comments in app/repository/backtest/models.py.
This script only generates the raw schema reference.
"""

import inspect
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import inspect as sa_inspect
from app.repository.backtest.database import Base
from app.repository.backtest import models  # noqa: F401 — registers models


def get_column_type(col):
    """Get a human-readable type string for a SQLAlchemy column."""
    type_name = type(col.type).__name__
    type_map = {
        "Integer": "INTEGER",
        "Text": "TEXT",
        "Float": "REAL",
        "Boolean": "BOOLEAN",
        "DateTime": "DATETIME",
        "Date": "DATE",
        "JSON": "JSON",
        "LargeBinary": "BLOB",
    }
    return type_map.get(type_name, type_name.upper())


def get_column_constraints(col):
    """Get constraint annotations for a column."""
    parts = []
    if col.primary_key:
        parts.append("PK")
    if col.autoincrement and col.primary_key:
        parts.append("AUTO")
    if col.nullable is False and not col.primary_key:
        parts.append("NOT NULL")
    if col.unique and not col.primary_key:
        parts.append("UNIQUE")
    if col.default is not None:
        default = col.default
        if hasattr(default, "arg"):
            arg = default.arg
            if callable(arg):
                parts.append(f"DEFAULT {arg.__name__}()")
            else:
                parts.append(f"DEFAULT {repr(arg)}")
    for fk in col.foreign_keys:
        parts.append(f"FK → {fk.target_fullname}")
    return ", ".join(parts)


def get_indexes(table):
    """Get index definitions for a table."""
    indexes = []
    for idx in table.indexes:
        cols = ", ".join(c.name for c in idx.columns)
        indexes.append(f"  - `{idx.name}` on ({cols})")
    return indexes


def get_relationships(mapper):
    """Get relationship info from a mapper."""
    rels = []
    for rel in mapper.relationships:
        cascade = rel.cascade.intersection({"all", "delete-orphan", "delete"})
        cascade_str = f" (cascade: {', '.join(cascade)})" if cascade else ""
        rels.append(f"  - `{rel.key}` → `{rel.mapper.class_.__name__}`{cascade_str}")
    return rels


def generate_table_doc(model_class):
    """Generate markdown documentation for a single model."""
    table = model_class.__table__
    mapper = sa_inspect(model_class)

    lines = [f"### {table.name}", ""]

    # Column table
    lines.append("| Column | Type | Constraints |")
    lines.append("|--------|------|-------------|")

    for col in table.columns:
        col_type = get_column_type(col)
        constraints = get_column_constraints(col)
        lines.append(f"| `{col.name}` | {col_type} | {constraints} |")

    # Indexes
    indexes = get_indexes(table)
    if indexes:
        lines.append("")
        lines.append("**Indexes:**")
        lines.extend(indexes)

    # Relationships
    rels = get_relationships(mapper)
    if rels:
        lines.append("")
        lines.append("**Relationships:**")
        lines.extend(rels)

    lines.append("")
    return "\n".join(lines)


def generate_full_doc():
    """Generate the complete database.md content."""
    # Collect all model classes in definition order
    model_classes = []
    for name, obj in inspect.getmembers(models):
        if (
            inspect.isclass(obj)
            and issubclass(obj, Base)
            and obj is not Base
            and hasattr(obj, "__tablename__")
        ):
            model_classes.append(obj)

    # Build table overview
    overview_rows = []
    for model in model_classes:
        table_name = model.__tablename__
        doc = (model.__doc__ or "").strip().split("\n")[0] if model.__doc__ else ""
        overview_rows.append(f"| `{table_name}` | {doc} |")

    lines = [
        "# Database Schema",
        "",
        "> Auto-generated from ORM models at `app/repository/backtest/models.py`.",
        "> **Do NOT edit this file manually.** Run `python scripts/gen_db_docs.py` to regenerate.",
        "> Design rationale lives as comments in the ORM model file.",
        "",
        "---",
        "",
        "## Tables Overview",
        "",
        "| Table | Description |",
        "|-------|-------------|",
    ]
    lines.extend(overview_rows)
    lines.append("")
    lines.append("---")
    lines.append("")

    # Generate per-table docs
    for model in model_classes:
        lines.append(generate_table_doc(model))
        lines.append("---")
        lines.append("")

    # Add key design notes
    lines.extend([
        "## Key Design Notes",
        "",
        "- **TEXT for money**: All monetary values stored as TEXT, parsed with Python `Decimal`",
        "- **BLOB compression**: equity_curve and drawdown_curve are zlib-compressed JSON",
        "- **Cascade deletes**: Deleting a Run cascades to RunConfig, RunResult, RunTimeseries, Trades, Tags",
        "- **Grid search**: grid_search_parent_id links child runs to parent. Deleting parent does NOT cascade to children.",
        "- **Lazy loading**: RunTimeseries in separate table, loaded only on demand",
        "",
        "See `app/repository/backtest/models.py` for full design rationale in code comments.",
    ])

    return "\n".join(lines)


def main():
    output_path = Path(__file__).resolve().parent.parent / "docs" / "database.md"
    content = generate_full_doc()
    output_path.write_text(content, encoding="utf-8")
    print(f"Generated {output_path} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
