"""Pure domain layer for the BTC RSI cross alert.

Public exports of the frozen models, exact reason constants, deterministic
event identity, and the two pure functions. This package is deliberately NOT
registered in ``app.trading.strategy.loader`` — it does not implement the
single-frame ``IStrategy`` contract and must never appear in the backtest UI
or database seed.
"""

from app.trading.strategy.btc_rsi_cross_alert.evaluator import (
    H1_PRICE_EMA_MINIMUM_ROWS,
    H4_PRICE_EMA_MINIMUM_ROWS,
    RETRYABLE_PREPARATION_REASONS,
    RSI_BUNDLE_MINIMUM_ROWS,
    TRIGGER_MINIMUM_ROWS,
    candle_close_time,
    evaluate_btc_rsi_cross,
    expected_h1_close_for,
    expected_h4_close_for,
    normalize_candle_open,
    prepare_btc_rsi_cross_input,
)
from app.trading.strategy.btc_rsi_cross_alert.m5_checker import (
    M5_TIMEFRAME,
    evaluate_m5_cross,
    prepare_m5_cross_input,
)
from app.trading.strategy.btc_rsi_cross_alert.m15_checker import (
    M15_TIMEFRAME,
    evaluate_m15_cross,
    prepare_m15_cross_input,
)
from app.trading.strategy.btc_rsi_cross_alert.models import (
    COMPONENT_NAME,
    DECISION_ALERT_FRESH_BULLISH_CROSS_H4_BULLISH,
    DECISION_ALERT_M5_BULLISH_ALIGNMENT_H4_BULLISH,
    DECISION_H1_CLOSE_NOT_ABOVE_EMA21,
    DECISION_H4_CLOSE_NOT_ABOVE_EMA21,
    DECISION_M5_CLOSE_NOT_ABOVE_EMA21,
    DECISION_M5_EMA_WMA_SPREAD_NOT_ABOVE_2,
    DECISION_M5_RSI21_NOT_BELOW_60,
    DECISION_M5_RSI_ALIGNMENT_NOT_BULLISH,
    DECISION_M5_WMA45_NOT_ABOVE_45,
    DECISION_M15_CLOSE_NOT_ABOVE_EMA21,
    DECISION_NO_FRESH_BULLISH_CROSS,
    DECISION_REASONS,
    EVENT_ID_PREFIX,
    EVENT_ID_SUFFIX_LENGTH,
    H1_DUPLICATE_OR_NON_INCREASING_TIME,
    H1_EXPECTED_CLOSE_MISSING,
    H1_INSUFFICIENT_CONTIGUOUS_HISTORY,
    H1_LIVE_CLOSE_UNCONFIRMED,
    H1_NON_FINITE_DATA,
    H4_DUPLICATE_OR_NON_INCREASING_TIME,
    H4_EXPECTED_CLOSE_MISSING,
    H4_INSUFFICIENT_CONTIGUOUS_HISTORY,
    H4_LIVE_CLOSE_UNCONFIRMED,
    H4_NON_FINITE_DATA,
    PREPARATION_READY,
    PREPARATION_REASONS,
    TRIGGER_CURRENT_ROW_MISSING,
    TRIGGER_DUPLICATE_OR_NON_INCREASING_TIME,
    TRIGGER_INSUFFICIENT_CONTIGUOUS_HISTORY,
    TRIGGER_NON_FINITE_DATA,
    TRIGGER_UNSUPPORTED_TIMEFRAME,
    BtcRsiCrossDecision,
    BtcRsiCrossInput,
    BtcRsiCrossPreparation,
    RsiBundlePoint,
    build_event_id,
    event_id_suffix,
)

__all__ = [
    "COMPONENT_NAME",
    "DECISION_ALERT_FRESH_BULLISH_CROSS_H4_BULLISH",
    "DECISION_ALERT_M5_BULLISH_ALIGNMENT_H4_BULLISH",
    "DECISION_H4_CLOSE_NOT_ABOVE_EMA21",
    "DECISION_H1_CLOSE_NOT_ABOVE_EMA21",
    "DECISION_M5_CLOSE_NOT_ABOVE_EMA21",
    "DECISION_M5_EMA_WMA_SPREAD_NOT_ABOVE_2",
    "DECISION_M5_RSI_ALIGNMENT_NOT_BULLISH",
    "DECISION_M5_RSI21_NOT_BELOW_60",
    "DECISION_M5_WMA45_NOT_ABOVE_45",
    "DECISION_M15_CLOSE_NOT_ABOVE_EMA21",
    "DECISION_NO_FRESH_BULLISH_CROSS",
    "DECISION_REASONS",
    "EVENT_ID_PREFIX",
    "EVENT_ID_SUFFIX_LENGTH",
    "H4_DUPLICATE_OR_NON_INCREASING_TIME",
    "H4_EXPECTED_CLOSE_MISSING",
    "H4_INSUFFICIENT_CONTIGUOUS_HISTORY",
    "H4_LIVE_CLOSE_UNCONFIRMED",
    "H4_NON_FINITE_DATA",
    "H1_DUPLICATE_OR_NON_INCREASING_TIME",
    "H1_EXPECTED_CLOSE_MISSING",
    "H1_INSUFFICIENT_CONTIGUOUS_HISTORY",
    "H1_LIVE_CLOSE_UNCONFIRMED",
    "H1_NON_FINITE_DATA",
    "H1_PRICE_EMA_MINIMUM_ROWS",
    "H4_PRICE_EMA_MINIMUM_ROWS",
    "M15_TIMEFRAME",
    "M5_TIMEFRAME",
    "PREPARATION_READY",
    "PREPARATION_REASONS",
    "RETRYABLE_PREPARATION_REASONS",
    "RSI_BUNDLE_MINIMUM_ROWS",
    "TRIGGER_MINIMUM_ROWS",
    "TRIGGER_CURRENT_ROW_MISSING",
    "TRIGGER_DUPLICATE_OR_NON_INCREASING_TIME",
    "TRIGGER_INSUFFICIENT_CONTIGUOUS_HISTORY",
    "TRIGGER_NON_FINITE_DATA",
    "TRIGGER_UNSUPPORTED_TIMEFRAME",
    "BtcRsiCrossDecision",
    "BtcRsiCrossInput",
    "BtcRsiCrossPreparation",
    "RsiBundlePoint",
    "build_event_id",
    "candle_close_time",
    "evaluate_btc_rsi_cross",
    "evaluate_m15_cross",
    "evaluate_m5_cross",
    "event_id_suffix",
    "expected_h4_close_for",
    "expected_h1_close_for",
    "normalize_candle_open",
    "prepare_btc_rsi_cross_input",
    "prepare_m15_cross_input",
    "prepare_m5_cross_input",
]
